# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_HIM_sdetect <- function(x, y, xquant, yquant, inv_rob_sdx, rob_sdy, inf_set, non_inf_set) {
    .Call(`_hidetify_rcpp_HIM_sdetect`, x, y, xquant, yquant, inv_rob_sdx, rob_sdy, inf_set, non_inf_set)
}

rcpp_asymHIM_sdetect <- function(x, y, xquant, yquant, inv_rob_sdx, rob_sdy, asymvec, inf_set, non_inf_set) {
    .Call(`_hidetify_rcpp_asymHIM_sdetect`, x, y, xquant, yquant, inv_rob_sdx, rob_sdy, asymvec, inf_set, non_inf_set)
}

arma_sample <- function(x, size, replace) {
    .Call(`_hidetify_arma_sample`, x, size, replace)
}

rcpp_setdiff <- function(x, y) {
    .Call(`_hidetify_rcpp_setdiff`, x, y)
}

rcpp_mask_swamp_stat <- function(x, y, xquant, yquant, inv_rob_sdx, rob_sdy, number_subset, size_subset, est_clean_set, asymvec) {
    .Call(`_hidetify_rcpp_mask_swamp_stat`, x, y, xquant, yquant, inv_rob_sdx, rob_sdy, number_subset, size_subset, est_clean_set, asymvec)
}

rcpp_shidetify <- function(x, y, xquant, yquant, inv_rob_sdx, rob_sdy, asymvec, row_indice) {
    .Call(`_hidetify_rcpp_shidetify`, x, y, xquant, yquant, inv_rob_sdx, rob_sdy, asymvec, row_indice)
}

